= Keyboard_DE ist eine Abwandlung und Ergänzung der "Keyboard Library for Arduino" für das Verwenden mit deutscher Tastaturbelegung =

=== https://github.com/arduino-libraries/Keyboard ===

= ******************************************************************************************************************************
Diese Bibliothek dient zum Erstellen von Sketches für Arduino/Genuino Leonardo und Micro, die als Eingabegräte für deutsche Windows-Maschinen funktionieren sollen. 
Die Modifikation der Ursprünglichen Keyboard-Library sorgt dafür, dass beim Kompilieren alle einfachen Tasten, die sich gegenüber der US-Tastaturbelegung unterscheiden, angepasst werden. 
Das python script finishGermanLayout.py sorgt schließlich dafür, dass alle Tasten, für deren Verwendung zusätzlich die Taste AltGr gedrückt sein muss, entsprechend im sketch implementiert werden.

== ACHTUNG ==

Dieses Script funktioniert NUR wenn Strings mit doppelten Anführungszeichen markiert sind also "String" ! Einfache Anführungszeichen, also 'String' führen zu einer fehlerhaften Ausgabe.
"Ä", "ä", "Ö", "ö", "Ü" und "ü" sowie "§", "´" und weitere nicht-ascii Zeichen werden leider mit diesem Workaround für eine deutsche Tastatur noch nicht unterstützt.

=== Anleitung ===

1. Kopiere den Ordner "Keyboard_DE" in deinen .../Arduino/Libraries/ - Ordner.  
   
2. Kopiere/Verschiebe das Script "finishGermanLayout.py" irgendwo hin, wo du es wieder findest, wenn du es brauchst. 

3. Binde die Bibliothek mit '#include "Keyboard_DE.h"' in dein Sketch ein. 
    
4. Kopiere dein Sketch als "input.ino" in den gleichen Ordner, in dem sich das script "finishGermanLayout.py" befindet und führe das Script aus (Gegebenenfalls musst du das Script noch ausführbar machen). 
Solltest du Windows verwenden und ggf. sogar kein Python installiert haben, kannst du alternativ auch die finishGermanLayout.exe ausführen.

5. Wenn alles richtig gemacht wurde, sollte im Ordner jetzt eine Datei Namens "finish.ino" erstellt worden sein. Diese ist dann so konvertiert, dass dein Arduino alle Zeichen richtig an einen PC mit Windows übergibt. Diese muss jetzt nurnoch mit Hilfe der Arduino IDE kompiliert und auf den Arduino geladen werden.

-- Alternativ funktioniert die experimental_Keyboard_DE Bibliothek ohne die zusätzliche Bearbeitung durch ein Python Scirpt. Allerdings bekomme ich damit leider kein "<", ">" und kein "|" hin... --

== Keyboard_DE is a modification from "Keyboard Library for Arduino" to use with german keyboard layout == 
=== https://github.com/arduino-libraries/Keyboard ===
This library is for compiling sketches for Arduino/Genuino Leonardo and Micro, which aim to act as a HID on windows devices with german keyboard layout.
The modification of the forked library keyboard changes the scannumbers of simpole characters to fit for german keyboard layout via compiling.
The python script finishGermanLayout.py edits the sketch to type the charakers, which require to press the AltGr key, correctly.


== Attention ==

this script only works when marking strings with double quaotation marks as "string" -- single quotation marks as 'string' wont output a file as expected --
allso german Umlaut characters "Ä", "ä", "Ö", "ö", "Ü" and "ü" and other non ascii characters are not supported by this workaround yet

== Instructions ==

1. copy the folder Keyboard_DE into your .../Arduino/Libraries/ - folder
2. copy/move the file "finischGermanLayout.py" anywhere, where you will find it, if you need it
3. add this library to your sketch with '#include "Keyboard_DE.h"'
4. copy your sketch as "input.ino" into the same directory as the "finishGermanLayout.py" script and run it (maybe you need tomake it executable first)
if you are using windows you can run the finishGermanLayout.exe instead
5. If everything went well, there should then be a "finish.ino" file in this directory as well, which contains the correct code to deliver all characters corryctly on windows devices - just compile and upload it via Arduino IDE

== License ==

This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.


